export type FeatureId = string;

/** Where an installed mod came from, pinned to the exact bytes that were installed. */
export interface MarketplaceSource {
  github: string;
  path: string;
  /** "namespace/slug" — the catalog's stable key for this mod. */
  modId: string;
  /** Commit the files were fetched from. Installs never track a branch. */
  commit: string;
  version: string;
  installedAt: string;
  /** sha256 of each installed file, for integrity and hash-based takedowns. */
  hashes: Record<string, string>;
}

export interface Manifest {
  id: FeatureId;
  name: string;
  description: string;
  matches: string[];
  entry: string;
  styles?: string;
  version: string;
  author?: string;
  createdAt: string;
  updatedAt: string;
  capabilities?: string[];
  source?: MarketplaceSource;
}

export interface Feature {
  manifest: Manifest;
  enabled: boolean;
  broken?: boolean;
}

/** One entry in marketplace/catalog.json, generated by .github/scripts/build-catalog.mjs. */
export interface CatalogMod {
  id: string;
  namespace: string;
  slug: string;
  path: string;
  name: string;
  description: string;
  matches: string[];
  entry: string;
  styles?: string;
  version: string;
  author: string;
  commit: string;
  updatedAt: string;
  sizeBytes: Record<string, number>;
  hashes: Record<string, string>;
  /** Hosts found in the source that the mod does not declare a match for. */
  externalHosts: string[];
  official: boolean;
  issue?: number;
}

/**
 * A mod the maintainer removed. `critical` force-disables copies that are
 * already installed; `warn` only shows a banner.
 */
export interface BlockEntry {
  id: string;
  reason: string;
  severity: "critical" | "warn";
  addedAt: string;
  hashes?: string[];
}

export interface Catalog {
  schemaVersion: number;
  repo: string;
  mods: CatalogMod[];
  blocklist: BlockEntry[];
}

export type Role = "user" | "assistant";

export interface ChatTurn {
  role: Role;
  content: unknown;
  ts: string;
  commit?: string;
}

export interface ApplyError {
  featureId: FeatureId;
  message: string;
  stack?: string;
  ts: string;
}
